version: "3.3"

services:
  qix-engine:
    image: qlikcore/engine:12.368.0
    restart: always
    command: |
      -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - 29076:9076
    volumes:
      - ./data:/data:rw
      