raw_data:
Load 
  Date,
  If(IsNull(feature), 0, feature) as feature,
  If(IsNull(enhancement), 0, enhancement) as enhancement,
  If(IsNull(maintenance), 0, maintenance) as maintenance,
  If(IsNull(admin), 0, admin) as admin
   from [lib://data/measurements.xlsx] 
(ooxml, embedded labels, table is data);

measurements:
Crosstable (Type, Size)
Load * resident raw_data;

week:
Load
  Date, 
  WeekDay(Date) as weekDay,
  week(Date, 0) as week
Resident measurements;

Drop Table raw_data;